# Reference: https://github.com/i3/i3/blob/next/etc/config


# Start AeroSpace at login
start-at-login = true

exec.inherit-env-vars = true

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true
non-empty-workspaces-root-containers-layout-on-startup = 'smart'

# Run Sketchybar together with AeroSpace
after-startup-command = [
    'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0' ,
    'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar'
]

exec-on-workspace-change = ['/bin/bash', '-c',
    '/opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[exec.env-vars]
PATH = '${HOME}/.nix-profile/bin:/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]
cmd-enter = 'exec-and-forget alacritty'
cmd-d = 'exec-and-forget emacsclient --eval "(emacs-everywhere)"'

cmd-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left'
cmd-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down'
cmd-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up'
cmd-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right'

cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'

cmd-alt-b = 'split horizontal'
cmd-alt-v = 'split vertical'

ctrl-cmd-f = 'fullscreen'

cmd-alt-s = 'layout v_accordion' # 'layout stacking' in i3
cmd-alt-t = 'layout h_accordion' # 'layout tabbed' in i3
cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

cmd-shift-f = 'layout floating tiling' # 'floating toggle' in i3

cmd-shift-m = 'move-workspace-to-monitor --wrap-around next'
cmd-shift-n = 'move-workspace-to-monitor --wrap-around prev'

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#cmd-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# cmd-a = 'focus parent'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

cmd-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
cmd-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
cmd-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
cmd-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
cmd-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
cmd-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
cmd-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
cmd-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
cmd-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
cmd-shift-0 = ['move-node-to-workspace 10', 'workspace 10']


cmd-shift-r = 'reload-config'

cmd-r = 'mode resize'


[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
