name: Cache
on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  populate:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        system:
          - { name: azura, platform: x86_64-linux }
          - { name: namira, platform: x86_64-linux }
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: NixInstaller
        uses: DeterminateSystems/determinate-nix-action@v3.11.2

      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:deploy-rs

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Build ${{ matrix.system.name }}
        run: |
          nix run nixpkgs#nixos-rebuild -- build --flake .#${{ matrix.system.name }}
